### PR TITLE
chore: add tailwindcss support to prettier

### PR DESCRIPTION
**Pull request by aykutkardas**
https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted

### CODE REVIEW

**Comment by dogagenc** [comment]
@aykutkardas This is nice to have. Thank you!

Can we explicitly add it to end of plugins in prettier config file to prevent possible conflicts between plugins?

https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins
https://github.com/sveltejs/prettier-plugin-svelte#usage-with-tailwind-prettier-plugin

**Comment by dogagenc** [comment]
@aykutkardas, I have not attempted it, but most likely it will not work with the `inlineClass` helper that we currently have. 

Is there any solution that you know of to fix this issue?

**Comment by aykutkardas** [comment]
> @aykutkardas, I have not attempted it, but most likely it will not work with the `inlineClass` helper that we currently have.
> 
> Is there any solution that you know of to fix this issue?
> 
> Edit: Or just will it work?

Actually, you don't need to make any changes.


image

**Comment by dogagenc** [comment]
> > @aykutkardas, I have not attempted it, but most likely it will not work with the `inlineClass` helper that we currently have.
> > Is there any solution that you know of to fix this issue?
> > Edit: Or just will it work?
> 
> Actually, you don't need to make any changes.
> 
> image

That's cool!

**Pull request merged**
